export const ROLES = {
  INSTRUCTOR: 'instructor',
  TEACHING_ASSISTANT: 'teaching_assistant', 
  TUTOR: 'tutor',
  STUDENT_LEADER: 'student_leader',
  STUDENT_STANDARD: 'student_standard'
};

export const PERMISSIONS = {
  VIEW_ALL_USERS: 'view_all_users',
  MANAGE_ROLES: 'manage_roles',
  VIEW_LOGS: 'view_logs',
  MANAGE_CLASS: 'manage_class',
  MANAGE_ATTENDANCE: 'manage_attendance',
  SUBMIT_REPORTS: 'submit_reports',
  VIEW_ASSIGNMENTS: 'view_assignments',
  ASSIST_STUDENTS: 'assist_students',
  VIEW_TEAM_PROGRESS: 'view_team_progress',
  SUBMIT_GROUP_JOURNAL: 'submit_group_journal',
  VIEW_PERSONAL_DATA: 'view_personal_data',
  SUBMIT_ATTENDANCE: 'submit_attendance'
};

export const ROLE_PERMISSIONS = {
  [ROLES.INSTRUCTOR]: [
    PERMISSIONS.VIEW_ALL_USERS,
    PERMISSIONS.MANAGE_ROLES,
    PERMISSIONS.VIEW_LOGS,
    PERMISSIONS.MANAGE_CLASS,
    PERMISSIONS.MANAGE_ATTENDANCE,
    PERMISSIONS.SUBMIT_REPORTS,
    PERMISSIONS.VIEW_ASSIGNMENTS,
    PERMISSIONS.ASSIST_STUDENTS,
    PERMISSIONS.VIEW_TEAM_PROGRESS,
    PERMISSIONS.SUBMIT_GROUP_JOURNAL,
    PERMISSIONS.VIEW_PERSONAL_DATA,
    PERMISSIONS.SUBMIT_ATTENDANCE
  ],
  [ROLES.TEACHING_ASSISTANT]: [
    PERMISSIONS.MANAGE_CLASS,
    PERMISSIONS.MANAGE_ATTENDANCE,
    PERMISSIONS.SUBMIT_REPORTS,
    PERMISSIONS.VIEW_ASSIGNMENTS,
    PERMISSIONS.ASSIST_STUDENTS,
    PERMISSIONS.VIEW_PERSONAL_DATA,
    PERMISSIONS.SUBMIT_ATTENDANCE
  ],
  [ROLES.TUTOR]: [
    PERMISSIONS.VIEW_ASSIGNMENTS,
    PERMISSIONS.ASSIST_STUDENTS,
    PERMISSIONS.VIEW_PERSONAL_DATA,
    PERMISSIONS.SUBMIT_ATTENDANCE
  ],
  [ROLES.STUDENT_LEADER]: [
    PERMISSIONS.VIEW_TEAM_PROGRESS,
    PERMISSIONS.SUBMIT_GROUP_JOURNAL,
    PERMISSIONS.VIEW_PERSONAL_DATA,
    PERMISSIONS.SUBMIT_ATTENDANCE
  ],
  [ROLES.STUDENT_STANDARD]: [
    PERMISSIONS.VIEW_PERSONAL_DATA,
    PERMISSIONS.SUBMIT_ATTENDANCE
  ]
};

export function hasPermission(userRole, permission) {
  return ROLE_PERMISSIONS[userRole]?.includes(permission) || false;
}
